
package org.example.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Banque_Service", targetNamespace = "http://Service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verser", targetNamespace = "http://Service.example.org/", className = "org.example.service.Verser")
    @ResponseWrapper(localName = "verserResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.VerserResponse")
    @Action(input = "http://Service.example.org/Banque_Service/verserRequest", output = "http://Service.example.org/Banque_Service/verserResponse")
    public int verser(
        @WebParam(name = "arg0", targetNamespace = "")
        Compte arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Float arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transfert", targetNamespace = "http://Service.example.org/", className = "org.example.service.Transfert")
    @ResponseWrapper(localName = "transfertResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.TransfertResponse")
    @Action(input = "http://Service.example.org/Banque_Service/transfertRequest", output = "http://Service.example.org/Banque_Service/transfertResponse")
    public int transfert(
        @WebParam(name = "arg0", targetNamespace = "")
        Compte arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Float arg1);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetComptesResponse")
    @Action(input = "http://Service.example.org/Banque_Service/getComptesRequest", output = "http://Service.example.org/Banque_Service/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.example.service.Historique>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHist", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetHist")
    @ResponseWrapper(localName = "getHistResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetHistResponse")
    @Action(input = "http://Service.example.org/Banque_Service/getHistRequest", output = "http://Service.example.org/Banque_Service/getHistResponse")
    public List<Historique> getHist(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retirer", targetNamespace = "http://Service.example.org/", className = "org.example.service.Retirer")
    @ResponseWrapper(localName = "retirerResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.RetirerResponse")
    @Action(input = "http://Service.example.org/Banque_Service/retirerRequest", output = "http://Service.example.org/Banque_Service/retirerResponse")
    public int retirer(
        @WebParam(name = "arg0", targetNamespace = "")
        Compte arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveCompte", targetNamespace = "http://Service.example.org/", className = "org.example.service.SaveCompte")
    @ResponseWrapper(localName = "saveCompteResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.SaveCompteResponse")
    @Action(input = "http://Service.example.org/Banque_Service/saveCompteRequest", output = "http://Service.example.org/Banque_Service/saveCompteResponse")
    public Compte saveCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        Compte arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActe", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetActe")
    @ResponseWrapper(localName = "getActeResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetActeResponse")
    @Action(input = "http://Service.example.org/Banque_Service/getActeRequest", output = "http://Service.example.org/Banque_Service/getActeResponse")
    public String getActe(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.GetCompteResponse")
    @Action(input = "http://Service.example.org/Banque_Service/getCompteRequest", output = "http://Service.example.org/Banque_Service/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exist", targetNamespace = "http://Service.example.org/", className = "org.example.service.Exist")
    @ResponseWrapper(localName = "existResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.ExistResponse")
    @Action(input = "http://Service.example.org/Banque_Service/existRequest", output = "http://Service.example.org/Banque_Service/existResponse")
    public boolean exist(
        @WebParam(name = "arg0", targetNamespace = "")
        Compte arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setHistorique", targetNamespace = "http://Service.example.org/", className = "org.example.service.SetHistorique")
    @ResponseWrapper(localName = "setHistoriqueResponse", targetNamespace = "http://Service.example.org/", className = "org.example.service.SetHistoriqueResponse")
    @Action(input = "http://Service.example.org/Banque_Service/setHistoriqueRequest", output = "http://Service.example.org/Banque_Service/setHistoriqueResponse")
    public int setHistorique(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
